### ISSUE TITLE
希望可以加入动态端口的选项....自己配置总是失败

### ISSUE THREAD

**Issue by SoYeonQwQ** [tracyone/v2ray.fun#12]
自己修改/etc/v2ray/config.json后就开不起来了...

**Comment by tracyone** [comment]
也就是  https://github.com/tracyone/v2ray.fun/issues/8

我也没有配置过，你可以把你配置发来看下

**Comment by SoYeonQwQ** [comment]
配置好后
启动服务会弹
Traceback (most recent call last):
  File "/usr/local/v2ray.fun/openport.py", line 5, in <module>
    import readjson
  File "/usr/local/v2ray.fun/readjson.py", line 15, in <module>
    ConfDns=config[u"dns"]
KeyError: u'dns'
Traceback (most recent call last):
  File "/usr/local/v2ray.fun/genclient.py", line 5, in <module>
    import readjson
  File "/usr/local/v2ray.fun/readjson.py", line 15, in <module>
    ConfDns=config[u"dns"]
KeyError: u'dns'
服务已重启！

但是仍然配置成功

**Comment by SoYeonQwQ** [comment]
相关配置 
    "inbound": {
        "port": 8080,
        "protocol": "vmess",
        "settings": {
            "udp": true,
            "clients": [
                {
                    "id": "d64c96a7-ca68-4f0f-af8b-89f2b1f857f4",
                    "level": 1,
                    "alterId": 233
                }
            ],
            "detour": {
                "to": "dynamic"
            }
        },
        "streamSettings": {
            "network": "kcp"
        }
    },
    "outbound": {
        "protocol": "freedom",
        "settings": {}
    },
    "inboundDetour": [
        {
            "protocol": "vmess",
            "port": "10000-20000",
            "tag": "dynamic",
            "settings": {
                "udp": true,
                "default": {
                    "level": 1,
                    "alterId": 32
                }
            },
            "allocate": {
                "strategy": "random",
                "concurrency": 2,
                "refresh": 5
            },
            "streamSettings": {
                "network": "kcp"
            }
        }
    ],
    "transport": {
        "kcpSettings": {
            "mtu": 1350,
            "tti": 50,
            "uplinkCapacity": 100,
            "downlinkCapacity": 100,
            "congestion": false,
            "readBufferSize": 2,
            "writeBufferSize": 2,
            "header": {
                "type": "wechat-video"
            }
        }
    },

**Comment by tracyone** [comment]
@SoYeonQwQ 你试下，我已经提交了，你update一下，然后cd /usr/local/v2ray.fun，然后git checkout dev，然后执行./install.sh，看看有没有什么建议意见

**Comment by SoYeonQwQ** [comment]
测试了一下,基本没什么问题了
修改动态端口相关配置也都ok

**Comment by SoYeonQwQ** [comment]
感谢你做出的贡献~

**Comment by tracyone** [comment]
已经合并到master分支，请知悉。
