### ISSUE TITLE
Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 35

### ISSUE THREAD

**Issue by zhezhe168** [tracyone/v2ray.fun#14]
Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 35

**Comment by tracyone** [comment]
麻烦你说清楚好吗，什么系统什么版本，出现问题，有点提问的智慧好吗？

**Comment by zhezhe168** [comment]
centos 7 系统，这几天出现的，之前同样这个系统没问题

**Comment by tracyone** [comment]
无法复现，关了。

建议重新安装一遍
