### ISSUE TITLE
你好，谢谢你的脚本，用的挺好，只是有个小问题

### ISSUE THREAD

**Issue by cheapssr** [tracyone/v2ray.fun#18]
运行一段时间之后，无法连通了，进vps启动一下就好了
这个是不是会自动停止运行呢
如果我安装超级守护的话，，怎么守护这个进程呢

**Comment by cheapssr** [comment]
补充一下，是运行一段时间之后，大概就十几个小时，就开始总是停了
centos 7.5 X64 minimal，无任何加速

**Comment by tracyone** [comment]
@Zhai2333 感觉没解决吧，虽然我没遇到过楼主的问题，但是的确没有守护进程吧？

**Comment by Zhai2333** [comment]
我可能记错了，临时解决方案crontab弄吧
