### ISSUE TITLE
【通告】正式支持生成vmess二维码图片

### ISSUE THREAD

**Issue by tracyone** [tracyone/v2ray.fun#24]
1，支持v2rayN & v2rayNG的2.x版本格式
2，支持ios客户端pepi的1.0.7版本格式

当点击菜单 **3. 查看服务端信息**的时候，就会生成两张qr图片，位于/root目录下

点击下面这个菜单，会询问你是否需要将qr图片通过sz传到本机。

**4.下载客户端配置文件**

**Comment by tracyone** [comment]
大家只需要更新本脚本就可享受到这个便捷了。

**Comment by tracyone** [comment]
听shadowrocket的作者说，shadowrocket也是支持v2rayN的二维码的

Pepi客户端有bug，其中的alterId是无法通过二维码倒入的，但是不影响上网..，改alterID也相对容易些。

**Comment by Zhai2333** [comment]
建议 Close 此 Issue。
