### ISSUE TITLE
反馈2个问题

### ISSUE THREAD

**Issue by ntgeralt** [tracyone/v2ray.fun#25]
首先感谢你制作的脚本。初次尝试，发现几个问题：

1：生成的vmess，用户v2rayN.exe 剪贴板导入，加密并不是none而是aes 128 gcm，会无法使用；

只有生成json客户端让v2rayN.exe 自定义导入才能用，但看日志发现时不时有fail句式出现。

2：生成json客户端似乎有语法问题，在koolshare lede v2ray客户端导入无法启动。

3：TLS模式后，生成的vmess也是无法让PC客户端使用，要另外手动修正。

**Comment by tracyone** [comment]
收到，请问你正在用的v2rayN的版本是多少呢，我是基于v2.x版本制作的vmess链接和二维码。

tls功能我一直没用过，如果可以，可以把修改前后的代码片段贴到这里。

非常感谢你的反馈。

**Comment by ntgeralt** [comment]
你好，v2ray 是最新的v2.11

另外发现medium也有v2ray.fun帖子，里面的一键脚本和你github这个不同，你们是同一人吗。
https://medium.com/@lastbus/v2ray-fun-%E5%A4%9A%E7%94%A8%E6%88%B7-6665bb845ae2

ps：12345固定端口不大合适，可以的话随机一个好些

**Comment by tracyone** [comment]
不是同个人。

不过原始作者都是同一个人，只不过原始作者有一天突然删掉了原始仓库，不继续了。我有点兴趣就继续了。

**Comment by tracyone** [comment]
第一个问题似乎是v2rayN的问题，正在确认中。

**Comment by ntgeralt** [comment]
我看到你root下服务端config.json自动生成的配置为
"alterId": 100, 
"security": "None", 

提个建议
 "security": 这里，服务端可以选择auto，客户端选什么都可以自动匹配；
"alterId": 选为32或更低可以获得更少的性能消耗

https://www.v2ray.com/chapter_02/protocols/vmess.html

**Comment by Zhai2333** [comment]
https://github.com/tracyone/v2ray.fun/issues/25#issuecomment-407771632
`"security": "auto"`已经 Merge。
请更新脚本。
