### ISSUE TITLE
安卓手机连上死活上不了网？

### ISSUE THREAD

**Issue by Handsome1080P** [tracyone/v2ray.fun#31]
使用的是GOOGLE play里面的V2RAYNG,配置文件完全正确，依旧不能上网，服务器log里面能看到accepted然后就没有下文了。电脑端能用

**Comment by Zhai2333** [comment]
请尝试BifrostV。

**Comment by Handsome1080P** [comment]
安卓上的每個關於V2RAY的軟件都試過了,不行。他們都是支持V2RAY 3.X的，v2ray.fun的服務端版本難道是2.X?

**Comment by tracyone** [comment]
@Handsome1080P 如果很久前装的，v2ray.fun是有可能是2.x，你可以更新v2ray fun，按照readme里面的方式。v2ray fun菜单里面也有更新的选项。

**Comment by Handsome1080P** [comment]
已經更新到最新的腳本了，但是依舊不能上網。連上後只有上傳數據，沒有下載0KB/ S

**Comment by tracyone** [comment]
把除了id，ip之外的配置贴出来来吧

**Comment by Handsome1080P** [comment]
平台是arm64,
!(1)[https://i.loli.net/2018/08/24/5b7fc8ffcb13e.png]

**Comment by Zhai2333** [comment]
尝试 https://install.direct/go.sh。

**Comment by Zhai2333** [comment]
尝试正确配置防火墙的 UDP。

**Comment by BraydenHung** [comment]
扫二维码同样是连接不上，Android端用的是v2rayng，不过PC端连接成功

**Comment by hisatsu** [comment]
{
 "outbound": {
  "streamSettings": {
   "network": "tcp", 
   "kcpSettings": null, 
   "wsSettings": null, 
   "tcpSettings": {
    "header": {
     "type": "http", 
     "request": {
      "path": [
       "/"
      ], 
      "version": "1.1", 
      "method": "GET", 
      "headers": {
       "Host": "www.apple.com", 
       "User-Agent": [
        "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36", 
        "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
       ], 
       "Connection": [
        "keep-alive"
       ], 
       "Pragma": "no-cache", 
       "Accept-Encoding": [
        "gzip, deflate"
       ]
      }
     }, 
     "response": {
      "status": "200", 
      "headers": {
       "Transfer-Encoding": [
        "chunked"
       ], 
       "Connection": [
        "keep-alive"
       ], 
       "Content-Type": [
        "application/octet-stream", 
        "video/mpeg"
       ], 
       "Pragma": "no-cache"
      }, 
      "reason": "OK", 
      "version": "1.1"
     }
    }, 
    "connectionReuse": true
   }, 
   "tlsSettings": {}, 
   "security": ""
  }, 
  "tag": "agentout", 
  "protocol": "vmess", 
  "mux": {
   "enabled": true
  }, 
  "settings": {
   "vnext": [
    {
     "users": [
      {
       "alterId": 100, 
       "security": "aes-128-gcm", 
       "id": ""
      }
     ], 
     "port": 13734, 
     "address": ""
    }
   ]
  }
 }, 
 "log": {
  "access": "", 
  "loglevel": "info", 
  "error": ""
 }, 
 "outboundDetour": [
  {
   "tag": "direct", 
   "protocol": "freedom", 
   "settings": {
    "response": null
   }
  }, 
  {
   "tag": "blockout", 
   "protocol": "blackhole", 
   "settings": {
    "response": {
     "type": "http"
    }
   }
  }
 ], 
 "inbound": {
  "streamSettings": null, 
  "settings": {
   "ip": "127.0.0.1", 
   "udp": true, 
   "clients": null, 
   "auth": "noauth"
  }, 
  "protocol": "socks", 
  "port": 1080, 
  "listen": "0.0.0.0"
 }, 
 "inboundDetour": null, 
 "routing": {
  "settings": {
   "rules": [
    {
     "ip": [
      "0.0.0.0/8", 
      "10.0.0.0/8", 
      "100.64.0.0/10", 
      "127.0.0.0/8", 
      "169.254.0.0/16", 
      "172.16.0.0/12", 
      "192.0.0.0/24", 
      "192.0.2.0/24", 
      "192.168.0.0/16", 
      "198.18.0.0/15", 
      "198.51.100.0/24", 
      "203.0.113.0/24", 
      "::1/128", 
      "fc00::/7", 
      "fe80::/10"
     ], 
     "domain": null, 
     "type": "field", 
     "port": null, 
     "outboundTag": "direct"
    }, 
    {
     "type": "chinaip", 
     "outboundTag": "direct"
    }, 
    {
     "type": "chinasites", 
     "outboundTag": "direct"
    }
   ], 
   "domainStrategy": "IPIfNonMatch"
  }, 
  "strategy": "rules"
 }, 
 "dns": {
  "servers": [
   "8.8.8.8", 
   "8.8.4.4", 
   "localhost"
  ]
 }
}


同样是PC可以，安卓不行
