### ISSUE TITLE
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - 执行错误

### ISSUE THREAD

**Issue by huang1982** [tracyone/v2ray.fun#35]
在 debian9 上全新安装的时候 因为curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - 这句会导致执行报错，无法安装nmp ，从而导致qrcoder无法安装，无法生成二维码

curl -sL https://deb.nodesource.com/setup_8.x |  bash  手动执行后，能顺利安装。但是脚本跟新后又会回到原来状态！

**Comment by tracyone** [comment]
fixed.请更新
