### ISSUE TITLE
建议加入兼容 CentOS 6

### ISSUE THREAD

**Issue by leitbogioro** [tracyone/v2ray.fun#36]
此脚本不兼容 CentOS 6 的原因，是CentOS 6 默认的 python 2.6 版本不支持安装 pillow 和 qrcode 两个用于生成客户端二维码的 python 组件，目前我通过采用强制升级 python 2.6 至 python 2.7 版本解决了这个问题，我的脚本项目地址在此，如果您有需要，可以考虑加入对 CentOS 6的兼容和支持。
https://github.com/leitbogioro/Install-python2.7-for-CentOS-6

**Comment by tracyone** [comment]
qrcode，我试了下，可以centos6.x，python版本是2.6.6

qrcode应该依赖nodejs，和python无关

```bash
    curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
	yum install  nodejs -y
    npm install -g qrcode

```

```bash
cat /etc/redhat-release
CentOS release 6.10 (Final)
python --version
Python 2.6.6
```

**Comment by tracyone** [comment]
qrcode和python没关系，整个仓库里面也没有调用pip命令啊。。

**Comment by leitbogioro** [comment]
当然有关系了，你生成 qrcode 的同时还要 pillow 组件，这两个都依赖 pip

**Comment by Zhai2333** [comment]
你全文查找 pip 试试？🤔

**Comment by Zhai2333** [comment]
https://github.com/nodesource/distributions/blob/master/OLDER_DISTROS.md
参考此篇。 @leitbogioro

**Comment by Zhai2333** [comment]
@sakz 参考楼上回答。
解决了 Node.js 的问题自然就可以了。

**Comment by Zhai2333** [comment]
找到为什么强制升级就能用了。
Node.js 需要使用 Python 2.7 作为依赖，安装后 Node.js 就能使用了。

**Comment by tracyone** [comment]
奇怪我全新centos 6.10系统，可以用啊。。。二维码生成正常

**Comment by forever8938** [comment]
那就砍掉二维码功能，反正不是必须的
