### ISSUE TITLE
你好 提示未知版本

### ISSUE THREAD

**Issue by silencebbb** [tracyone/v2ray.fun#4]
你好

使用v2ray-v3.1-windows-64 提示未知版本

[Info]App|Proxyman|Inbound: connection ends > Proxy|Socks: failed to read request > Proxy|Socks: unknown Socks version: 71

谢谢

**Comment by silencebbb** [comment]
手机使用v2rayNG 没有问题。

**Comment by Zhai2333** [comment]
你的 V2ray 自身配置问题。
