### ISSUE TITLE
不知道是我操作问题还是怎么的

### ISSUE THREAD

**Issue by InoriHimea** [tracyone/v2ray.fun#40]
当我修改了配置，比如加密方式，比如开启tls，设置域名，结果导出的连接却还是ip地址的，这个问题会是应为没有刷新嘛。代码里头没有相关操作，而且我导入v2rayN中，然后把ip自己改成域名，软件显示的连接确实不同

**Comment by Zhai2333** [comment]
有时间会改。
@tracyone 加标签 [TODO]

**Comment by tracyone** [comment]
解决了，试一下。
