### ISSUE TITLE
Failed to start v2ray.service: Unit v2ray.service not found.

### ISSUE THREAD

**Issue by xxhjkl** [tracyone/v2ray.fun#41]
Failed to start v2ray.service: Unit v2ray.service not found.
脚本跑完了。启动不起。debian8 debian9 都这个错误

**Comment by zi4086** [comment]
对的 我也是..一直重装系统 试了好久都这样

**Comment by tracyone** [comment]
非本仓库问题，
貌似已经修复，无法复现了，如果还不行，解压附件的文件到`/etc/systemd/system`路径下。

[v2ray.service.tar.gz](https://github.com/tracyone/v2ray.fun/files/2446628/v2ray.service.tar.gz)
