### ISSUE TITLE
为什么脚本自动跳啊，我都没按回车´_＞`

### ISSUE THREAD

**Issue by zhz1237ok** [tracyone/v2ray.fun#43]
1.更改UUID
2.更改主端口
3.更改加密方式
4.更改传输方式
5.更改TLS设置
6.更改广告拦截功能
7.更改alterId
8.更改动态端口
请输入数字选择功能：

请选择： 1

/usr/local/bin/v2ray: line 126: python: command not found
/usr/local/bin/v2ray: line 127: python: command not found
Failed to restart v2ray.service: Unit v2ray.service not found.

UUID修改成功！

我就刚输入1，还没按回车，就自动变成这样了

**Comment by tracyone** [comment]
问题不是自动跳，问题是你连python都没有
