### ISSUE TITLE
Tls 如何配置，我按要求来的，上不了！

### ISSUE THREAD

**Issue by thelighter** [tracyone/v2ray.fun#48]
1 开启tls 2 绑定域名 3 域名解析 ip www主机名 
现在上不去  求教了 大佬

**Comment by Zhai2333** [comment]
TLS 功能目前不稳定。
是什么协议使用 TLS 呢？
如需手动设置请参阅[白话文教程](https://toutyrater.github.io/advanced/tls.html)。

**Comment by thelighter** [comment]
谢谢
