### ISSUE TITLE
建议可指定临时文件目录，/tmp没空间

### ISSUE THREAD

**Issue by anphorea** [tracyone/v2ray.fun#51]
在bandwagonhost上部署这个脚本的时候，发现报错说空间不够
结果/tmp是单独挂载的，只有几M，确实放不下v2ray的下载档
脚本前部能否加入临时路径设置选项？
谢谢

**Comment by Zhai2333** [comment]
这个是 V2ray 官方的安装脚本的路径，我们无法解决这个问题。

**Comment by anphorea** [comment]
OK
我基于233boy的脚本自己硬改了一下子，可以用了。
https://github.com/nanoteko/v2ray
感谢~
