### ISSUE TITLE
可以增加重启后自动运行v2ray吗？

### ISSUE THREAD

**Issue by Alvin9999** [tracyone/v2ray.fun#52]
谢谢哦，感觉这样方便些

**Comment by Zhai2333** [comment]
尝试 `systemctl enable v2ray` 。

**Comment by tracyone** [comment]
我刚刚试了下，重启之后有运行，要不更新v2ray.fun?

之前我特意有注意到这个问题。

**Comment by Alvin9999** [comment]
@Zhai2333 谢谢，按照你的方法已解决
@tracyone  那应该是我没有更新脚本的原因，感谢提醒。
