### ISSUE TITLE
Centos7启动失败

### ISSUE THREAD

**Issue by kevinkingdomviva** [tracyone/v2ray.fun#54]
请帮忙看看，或者留一下联系方式我直接把机器给你发过去

Redirecting to /bin/systemctl status v2ray.service
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Wed 2018-12-26 18:20:40 UTC; 9min ago
  Process: 6323 ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (code=exited, status=255)
 Main PID: 6323 (code=exited, status=255)

Dec 26 18:20:40 vultr.guest systemd[1]: v2ray.service: main process exited, code=exited, status=255/n/a
Dec 26 18:20:40 vultr.guest systemd[1]: Unit v2ray.service entered failed state.
Dec 26 18:20:40 vultr.guest systemd[1]: v2ray.service failed.
Dec 26 18:20:40 vultr.guest systemd[1]: v2ray.service holdoff time over, scheduling restart.
Dec 26 18:20:40 vultr.guest systemd[1]: Stopped V2Ray Service.
Dec 26 18:20:40 vultr.guest systemd[1]: start request repeated too quickly for v2ray.service
Dec 26 18:20:40 vultr.guest systemd[1]: Failed to start V2Ray Service.
Dec 26 18:20:40 vultr.guest systemd[1]: Unit v2ray.service entered failed state.
Dec 26 18:20:40 vultr.guest systemd[1]: v2ray.service failed.

**Comment by ilovebamboo** [comment]
不支持

**Comment by Zhai2333** [comment]
执行 `cat /etc/systemd/system/v2ray.service` 并把结果贴上来。
或者请尝试重新生成 `config.json`。
