### ISSUE TITLE
修改服务器ip后，面板中的ip无法更新

### ISSUE THREAD

**Issue by love1980s** [tracyone/v2ray.fun#55]
腾讯云香港服务器，安装后运行正常，一段时间后我换了一个新的服务器ip，但面板中的ip无法更新，卸载重装后，面板中还是现实老的ip

而且，在v2ray 客户端中，配置为 新ip 也无法正常连接。

**Comment by Zhai2333** [comment]
请尝试查看 /etc/v2ray/config.json 中的 listen 是否是原 IP，如果是的话请更改。

**Comment by tracyone** [comment]
你说的“面板”是什么？你好像搞错仓库，出门右转，谢谢
