### ISSUE TITLE
添加了inbounddetour启动报错了

### ISSUE THREAD

**Issue by fengmikaelson** [tracyone/v2ray.fun#7]
{
 "outbound": {
  "streamSettings": null, 
  "tag": null, 
  "protocol": "freedom", 
  "mux": null, 
  "settings": null
 }, 
 "log": {
  "access": "/var/log/v2ray/access.log", 
  "loglevel": "info", 
  "error": "/var/log/v2ray/error.log"
 }, 
 "inboundDetour": {
  "protocol": "vmess",
  "port": "10000-20000", // 端口范围
  "tag": "detour",       // 此传入协议的标签，在第二部分中会用到
  "settings": {
    "default": {
      "level": 0,
      "alterId": 100
    }
  }, 
  "allocate": {            // 分配模式
    "strategy": "random",  // 随机开启
    "concurrency": 2,      // 同时开放两个端口
    "refresh": 2           // 每五分钟刷新一次
  },
 "inbound": {
  "streamSettings": {
   "network": "kcp", 
   "kcpSettings": {
    "uplinkCapacity": 100, 
    "downlinkCapacity": 100, 
    "readBufferSize": 2, 
    "mtu": 1350, 
    "header": {
     "request": null, 
     "type": "none", 
     "response": null
    }, 
    "tti": 50, 
    "congestion": false, 
    "writeBufferSize": 2
   }, 
   "wsSettings": null, 
   "tcpSettings": null, 
   "tlsSettings": {}, 
   "security": ""
  }, 
  "listen": null, 
  "protocol": "vmess", 
  "port": 10086, 
  "settings": {
   "ip": null, 
   "udp": true, 
   "clients": [
    {
     "alterId": 100, 
     "security": "aes-128-gcm", 
     "id": "b4dc4599-8681-49d5-ba5d-e60397405e40"
    }
   ], 
   "detour": {        // 绕路设置
      "to": "detour"   // 指定绕路协议的标签，要和“一”中的标签一样
    },
   "auth": null
  }
 }, 
 "outboundDetour": [
  {
   "tag": "direct", 
   "protocol": "freedom", 
   "settings": null
  }, 
  {
   "tag": "blocked", 
   "protocol": "blackhole", 
   "settings": null
  }
 ], 
 "routing": {
  "strategy": "rules", 
  "settings": {
   "rules": [
    {
     "ip": [
      "0.0.0.0/8", 
      "10.0.0.0/8", 
      "100.64.0.0/10", 
      "127.0.0.0/8", 
      "169.254.0.0/16", 
      "172.16.0.0/12", 
      "192.0.0.0/24", 
      "192.0.2.0/24", 
      "192.168.0.0/16", 
      "198.18.0.0/15", 
      "198.51.100.0/24", 
      "203.0.113.0/24", 
      "::1/128", 
      "fc00::/7", 
      "fe80::/10"
     ], 
     "domain": null, 
     "type": "field", 
     "port": null, 
     "outboundTag": "blocked"
    }, 
    {
     "domain": [], 
     "type": "field", 
     "outboundTag": "direct"
    }
   ], 
   "domainStrategy": null
  }
 }, 
 "dns": null
}

**Comment by YLWS-4617** [comment]
请不要在json里面加入中文注释，谢谢合作。我觉得很无语..

**Comment by tracyone** [comment]
解决，更新到最新
