### ISSUE TITLE
[Feature Request]  inboundDetour configuration

### ISSUE THREAD

**Issue by nylqd** [tracyone/v2ray.fun#8]
This script seems do not have inboundDetour config function, is there any chance to add inboundDetour configuration, that would be great!

thx a lot.

现在脚本中似乎并没有动态端口的相关配置，后续开发中能否考虑添加动态端口配置的功能，希望作者加以考虑了，谢谢！

**Comment by xuefengliang** [comment]
这个建议不错，有另外一个一键脚本已经实现

**Comment by tracyone** [comment]
你说的是这个功能么？https://toutyrater.github.io/advanced/dynamicport.html

非常有趣，我试试。
